[build]
  publish = "."
  command = "echo 'Static site - no build required'"

# Configuración de funciones Netlify
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Configuración de redirects para SPA
[[redirects]]
  from = "/"
  to = "/static-app.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/static-app.html"
  status = 200

[[redirects]]
  from = "/converter"
  to = "/static-app.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https://p2p.binance.com; img-src 'self' data:;"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers para archivos HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Variables de entorno
[context.production.environment]
  NODE_ENV = "production"
  
[context.deploy-preview.environment]
  NODE_ENV = "development"