[build]
  # Directorio de publicación (donde están los archivos estáticos)
  publish = "."
  
  # Comando de build (no necesario para sitio estático)
  command = "echo 'Sitio estático - no requiere build'"

[build.environment]
  # Variables de entorno para el build
  NODE_VERSION = "18"

# Configuración de redirects y rewrites
[[redirects]]
  # Redirigir todas las rutas no encontradas al index
  from = "/*"
  to = "/index_static.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https://p2p.binance.com;"

# Configuración de caché
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"